trusted:
  - freekmurze
  - '@spatie'

events:
  issue.opened:
    - action: ModifyIssueContent
      params: [$(issue.number), '{{original_text}}<br><br>_issue created by an untrusted author. closing issue._']
      
    - action: CreateIssueComment
      params: [$(issue.number), '@$(sender.login), you are not a trusted issue author.  Closing issue.']

    - action: AddIssueLabel
      condition: untrusted
      params: [$(issue.number), 'untrusted']
      
    - action: AddIssueLabel
      condition: trusted
      params: [$(issue.number), 'trusted']

    - action: CloseIssue
      params: [$(issue.number)]

  issue.reopened:
    - action: CloseIssue
      condition: untrusted
      params: [$(issue.number)]

  issue_comment.created:
    - action: ModifyIssueComment
      condition: untrusted && sender.login != comment.user.login
      params: [$(comment.id), '{{original_comment}}<br>--<br>This comment was updated by the trusted-issue-authors bot.']
   
   - action: ModifyIssueComment
     condition: untrusted
     params: [$(comment.id), '{{original_comment}}<br><br>the contents of this comment has been modified!']
