trusted:
  - freekmurze
  - '@spatie'

events:
  issue.opened:
    - action: CreateIssueComment
      params: [$(issue.number), '@$(sender.login), you are not a trusted issue author.  Closing issue.']

    - action: AddIssueLabel
      condition: untrusted
      params: [$(issue.number), 'untrusted']

    - action: CloseIssue
      params: [$(issue.number)]

  issue.reopened:
    - action: CloseIssue
      condition: untrusted
      params: [$(issue.number)]

  issue_comment.created:
    - action: ModifyIssueComment
      params: [$(comment.id), '{{original_comment}}\n\n---\n\nThis comment was updated by the trusted-issue-authors bot.']
