trusted:
  - freekmurze
  - '@spatie'

events:
  issue.opened:
    - action: ModifyIssueContent
      params: [$(issue.number), '{{original_text}}<br><br>_issue created by an untrusted author. closing issue._']
      
    - action: CreateIssueComment
      params: [$(issue.number), '@$(sender.login), you are not a trusted issue author.  Closing issue.']

    - action: AddIssueLabel
      condition: untrusted
      params: [$(issue.number), 'untrusted']

    - action: CloseIssue
      params: [$(issue.number)]

  issue.reopened:
    - action: CloseIssue
      condition: untrusted
      params: [$(issue.number)]

  issue_comment.created:
    - action: ModifyIssueComment
      params: [$(comment.id), '{{original_comment}}<br>---<br>_This comment was updated by the trusted-issue-authors bot._']
