trusted:
  - freekmurze
  - '@spatie'

events:
  issue.opened:
    - action: CreateIssueComment
      params: [$(issue.number), '@$(sender.login) is not a trusted issue author! Issue automatically closed.']
    - action: CloseIssue
      params: [$(issue.number)]

  issue.reopened:
    - action: CloseIssue
      params: [$(issue.number)]

  issue_comment.created:
#    - action: DeleteIssueComment
#      params: [$(comment.id)]
